---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Machine
metadata:
  name: worker-example
  namespace: test
  generateName: vs-worker-
  labels:
    sigs.k8s.io/cluster-api-cluster: tb-asg-35
    sigs.k8s.io/cluster-api-machine-role: infra
    sigs.k8s.io/cluster-api-machine-type: worker
spec:
  providerSpec:
    value:
      apiVersion: baremetalproviderconfig/v1alpha1
      ignKey: /somewhere/worker.ign
      ipmi:
        hostAddress: 10.19.110.18
        username: ADMIN
        password: ADMIN
        bootDevice: cdrom
      kind: BaremetalMachineProviderSpec
  versions:
    kubelet: ""
    controlPlane: ""