---
apiVersion: machine.openshift.io/v1beta1
kind: Machine
metadata:
  name: worker-example
  namespace: test
  generateName: vs-worker-
  labels:
    machine.openshift.io/cluster-api-cluster: tb-asg-35
    machine.openshift.io/cluster-api-machine-role: infra
    machine.openshift.io/cluster-api-machine-type: worker
spec:
  providerSpec:
    value:
      apiVersion: baremetalproviderconfig/v1alpha1
      ignKey: /somewhere/worker.ign
      ipmi:
        hostAddress: 10.19.110.18
        username: ADMIN
        password: ADMIN
        bootDevice: pxe
      kind: BaremetalMachineProviderSpec
  versions:
    kubelet: ""
    controlPlane: ""
