/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	baremetalproviderconfigv1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	versioned "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/clientset/versioned"
	internalinterfaces "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/listers/baremetalproviderconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BaremetalMachineProviderConfigInformer provides access to a shared informer and lister for
// BaremetalMachineProviderConfigs.
type BaremetalMachineProviderConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BaremetalMachineProviderConfigLister
}

type baremetalMachineProviderConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBaremetalMachineProviderConfigInformer constructs a new informer for BaremetalMachineProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBaremetalMachineProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBaremetalMachineProviderConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBaremetalMachineProviderConfigInformer constructs a new informer for BaremetalMachineProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBaremetalMachineProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BaremetalproviderconfigV1alpha1().BaremetalMachineProviderConfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BaremetalproviderconfigV1alpha1().BaremetalMachineProviderConfigs(namespace).Watch(options)
			},
		},
		&baremetalproviderconfigv1alpha1.BaremetalMachineProviderConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *baremetalMachineProviderConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBaremetalMachineProviderConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *baremetalMachineProviderConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&baremetalproviderconfigv1alpha1.BaremetalMachineProviderConfig{}, f.defaultInformer)
}

func (f *baremetalMachineProviderConfigInformer) Lister() v1alpha1.BaremetalMachineProviderConfigLister {
	return v1alpha1.NewBaremetalMachineProviderConfigLister(f.Informer().GetIndexer())
}
