/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	baremetalproviderconfigv1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	versioned "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/clientset/versioned"
	internalinterfaces "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/listers/baremetalproviderconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BaremetalProviderConfigInformer provides access to a shared informer and lister for
// BaremetalProviderConfigs.
type BaremetalProviderConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BaremetalProviderConfigLister
}

type baremetalProviderConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBaremetalProviderConfigInformer constructs a new informer for BaremetalProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBaremetalProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBaremetalProviderConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBaremetalProviderConfigInformer constructs a new informer for BaremetalProviderConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBaremetalProviderConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BaremetalproviderconfigV1alpha1().BaremetalProviderConfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BaremetalproviderconfigV1alpha1().BaremetalProviderConfigs(namespace).Watch(options)
			},
		},
		&baremetalproviderconfigv1alpha1.BaremetalProviderConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *baremetalProviderConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBaremetalProviderConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *baremetalProviderConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&baremetalproviderconfigv1alpha1.BaremetalProviderConfig{}, f.defaultInformer)
}

func (f *baremetalProviderConfigInformer) Lister() v1alpha1.BaremetalProviderConfigLister {
	return v1alpha1.NewBaremetalProviderConfigLister(f.Informer().GetIndexer())
}
