/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBaremetalMachineProviderSpecs implements BaremetalMachineProviderSpecInterface
type FakeBaremetalMachineProviderSpecs struct {
	Fake *FakeBaremetalproviderconfigV1alpha1
	ns   string
}

var baremetalmachineproviderspecsResource = schema.GroupVersionResource{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Resource: "baremetalmachineproviderspecs"}

var baremetalmachineproviderspecsKind = schema.GroupVersionKind{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Kind: "BaremetalMachineProviderSpec"}

// Get takes name of the baremetalMachineProviderSpec, and returns the corresponding baremetalMachineProviderSpec object, and an error if there is any.
func (c *FakeBaremetalMachineProviderSpecs) Get(name string, options v1.GetOptions) (result *v1alpha1.BaremetalMachineProviderSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(baremetalmachineproviderspecsResource, c.ns, name), &v1alpha1.BaremetalMachineProviderSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderSpec), err
}

// List takes label and field selectors, and returns the list of BaremetalMachineProviderSpecs that match those selectors.
func (c *FakeBaremetalMachineProviderSpecs) List(opts v1.ListOptions) (result *v1alpha1.BaremetalMachineProviderSpecList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(baremetalmachineproviderspecsResource, baremetalmachineproviderspecsKind, c.ns, opts), &v1alpha1.BaremetalMachineProviderSpecList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BaremetalMachineProviderSpecList{ListMeta: obj.(*v1alpha1.BaremetalMachineProviderSpecList).ListMeta}
	for _, item := range obj.(*v1alpha1.BaremetalMachineProviderSpecList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested baremetalMachineProviderSpecs.
func (c *FakeBaremetalMachineProviderSpecs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(baremetalmachineproviderspecsResource, c.ns, opts))

}

// Create takes the representation of a baremetalMachineProviderSpec and creates it.  Returns the server's representation of the baremetalMachineProviderSpec, and an error, if there is any.
func (c *FakeBaremetalMachineProviderSpecs) Create(baremetalMachineProviderSpec *v1alpha1.BaremetalMachineProviderSpec) (result *v1alpha1.BaremetalMachineProviderSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(baremetalmachineproviderspecsResource, c.ns, baremetalMachineProviderSpec), &v1alpha1.BaremetalMachineProviderSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderSpec), err
}

// Update takes the representation of a baremetalMachineProviderSpec and updates it. Returns the server's representation of the baremetalMachineProviderSpec, and an error, if there is any.
func (c *FakeBaremetalMachineProviderSpecs) Update(baremetalMachineProviderSpec *v1alpha1.BaremetalMachineProviderSpec) (result *v1alpha1.BaremetalMachineProviderSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(baremetalmachineproviderspecsResource, c.ns, baremetalMachineProviderSpec), &v1alpha1.BaremetalMachineProviderSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderSpec), err
}

// Delete takes name of the baremetalMachineProviderSpec and deletes it. Returns an error if one occurs.
func (c *FakeBaremetalMachineProviderSpecs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(baremetalmachineproviderspecsResource, c.ns, name), &v1alpha1.BaremetalMachineProviderSpec{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBaremetalMachineProviderSpecs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(baremetalmachineproviderspecsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BaremetalMachineProviderSpecList{})
	return err
}

// Patch applies the patch and returns the patched baremetalMachineProviderSpec.
func (c *FakeBaremetalMachineProviderSpecs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BaremetalMachineProviderSpec, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(baremetalmachineproviderspecsResource, c.ns, name, data, subresources...), &v1alpha1.BaremetalMachineProviderSpec{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderSpec), err
}
