/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBaremetalProviderConfigs implements BaremetalProviderConfigInterface
type FakeBaremetalProviderConfigs struct {
	Fake *FakeBaremetalproviderconfigV1alpha1
	ns   string
}

var baremetalproviderconfigsResource = schema.GroupVersionResource{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Resource: "baremetalproviderconfigs"}

var baremetalproviderconfigsKind = schema.GroupVersionKind{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Kind: "BaremetalProviderConfig"}

// Get takes name of the baremetalProviderConfig, and returns the corresponding baremetalProviderConfig object, and an error if there is any.
func (c *FakeBaremetalProviderConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.BaremetalProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(baremetalproviderconfigsResource, c.ns, name), &v1alpha1.BaremetalProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalProviderConfig), err
}

// List takes label and field selectors, and returns the list of BaremetalProviderConfigs that match those selectors.
func (c *FakeBaremetalProviderConfigs) List(opts v1.ListOptions) (result *v1alpha1.BaremetalProviderConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(baremetalproviderconfigsResource, baremetalproviderconfigsKind, c.ns, opts), &v1alpha1.BaremetalProviderConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BaremetalProviderConfigList{ListMeta: obj.(*v1alpha1.BaremetalProviderConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.BaremetalProviderConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested baremetalProviderConfigs.
func (c *FakeBaremetalProviderConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(baremetalproviderconfigsResource, c.ns, opts))

}

// Create takes the representation of a baremetalProviderConfig and creates it.  Returns the server's representation of the baremetalProviderConfig, and an error, if there is any.
func (c *FakeBaremetalProviderConfigs) Create(baremetalProviderConfig *v1alpha1.BaremetalProviderConfig) (result *v1alpha1.BaremetalProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(baremetalproviderconfigsResource, c.ns, baremetalProviderConfig), &v1alpha1.BaremetalProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalProviderConfig), err
}

// Update takes the representation of a baremetalProviderConfig and updates it. Returns the server's representation of the baremetalProviderConfig, and an error, if there is any.
func (c *FakeBaremetalProviderConfigs) Update(baremetalProviderConfig *v1alpha1.BaremetalProviderConfig) (result *v1alpha1.BaremetalProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(baremetalproviderconfigsResource, c.ns, baremetalProviderConfig), &v1alpha1.BaremetalProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalProviderConfig), err
}

// Delete takes name of the baremetalProviderConfig and deletes it. Returns an error if one occurs.
func (c *FakeBaremetalProviderConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(baremetalproviderconfigsResource, c.ns, name), &v1alpha1.BaremetalProviderConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBaremetalProviderConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(baremetalproviderconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BaremetalProviderConfigList{})
	return err
}

// Patch applies the patch and returns the patched baremetalProviderConfig.
func (c *FakeBaremetalProviderConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BaremetalProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(baremetalproviderconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BaremetalProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalProviderConfig), err
}
