/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBaremetalMachineProviderConfigs implements BaremetalMachineProviderConfigInterface
type FakeBaremetalMachineProviderConfigs struct {
	Fake *FakeBaremetalproviderconfigV1alpha1
	ns   string
}

var baremetalmachineproviderconfigsResource = schema.GroupVersionResource{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Resource: "baremetalmachineproviderconfigs"}

var baremetalmachineproviderconfigsKind = schema.GroupVersionKind{Group: "baremetalproviderconfig.k8s.io", Version: "v1alpha1", Kind: "BaremetalMachineProviderConfig"}

// Get takes name of the baremetalMachineProviderConfig, and returns the corresponding baremetalMachineProviderConfig object, and an error if there is any.
func (c *FakeBaremetalMachineProviderConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(baremetalmachineproviderconfigsResource, c.ns, name), &v1alpha1.BaremetalMachineProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderConfig), err
}

// List takes label and field selectors, and returns the list of BaremetalMachineProviderConfigs that match those selectors.
func (c *FakeBaremetalMachineProviderConfigs) List(opts v1.ListOptions) (result *v1alpha1.BaremetalMachineProviderConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(baremetalmachineproviderconfigsResource, baremetalmachineproviderconfigsKind, c.ns, opts), &v1alpha1.BaremetalMachineProviderConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BaremetalMachineProviderConfigList{ListMeta: obj.(*v1alpha1.BaremetalMachineProviderConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.BaremetalMachineProviderConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested baremetalMachineProviderConfigs.
func (c *FakeBaremetalMachineProviderConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(baremetalmachineproviderconfigsResource, c.ns, opts))

}

// Create takes the representation of a baremetalMachineProviderConfig and creates it.  Returns the server's representation of the baremetalMachineProviderConfig, and an error, if there is any.
func (c *FakeBaremetalMachineProviderConfigs) Create(baremetalMachineProviderConfig *v1alpha1.BaremetalMachineProviderConfig) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(baremetalmachineproviderconfigsResource, c.ns, baremetalMachineProviderConfig), &v1alpha1.BaremetalMachineProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderConfig), err
}

// Update takes the representation of a baremetalMachineProviderConfig and updates it. Returns the server's representation of the baremetalMachineProviderConfig, and an error, if there is any.
func (c *FakeBaremetalMachineProviderConfigs) Update(baremetalMachineProviderConfig *v1alpha1.BaremetalMachineProviderConfig) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(baremetalmachineproviderconfigsResource, c.ns, baremetalMachineProviderConfig), &v1alpha1.BaremetalMachineProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderConfig), err
}

// Delete takes name of the baremetalMachineProviderConfig and deletes it. Returns an error if one occurs.
func (c *FakeBaremetalMachineProviderConfigs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(baremetalmachineproviderconfigsResource, c.ns, name), &v1alpha1.BaremetalMachineProviderConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBaremetalMachineProviderConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(baremetalmachineproviderconfigsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BaremetalMachineProviderConfigList{})
	return err
}

// Patch applies the patch and returns the patched baremetalMachineProviderConfig.
func (c *FakeBaremetalMachineProviderConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(baremetalmachineproviderconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.BaremetalMachineProviderConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BaremetalMachineProviderConfig), err
}
