/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BaremetalMachineProviderSpecLister helps list BaremetalMachineProviderSpecs.
type BaremetalMachineProviderSpecLister interface {
	// List lists all BaremetalMachineProviderSpecs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.BaremetalMachineProviderSpec, err error)
	// BaremetalMachineProviderSpecs returns an object that can list and get BaremetalMachineProviderSpecs.
	BaremetalMachineProviderSpecs(namespace string) BaremetalMachineProviderSpecNamespaceLister
	BaremetalMachineProviderSpecListerExpansion
}

// baremetalMachineProviderSpecLister implements the BaremetalMachineProviderSpecLister interface.
type baremetalMachineProviderSpecLister struct {
	indexer cache.Indexer
}

// NewBaremetalMachineProviderSpecLister returns a new BaremetalMachineProviderSpecLister.
func NewBaremetalMachineProviderSpecLister(indexer cache.Indexer) BaremetalMachineProviderSpecLister {
	return &baremetalMachineProviderSpecLister{indexer: indexer}
}

// List lists all BaremetalMachineProviderSpecs in the indexer.
func (s *baremetalMachineProviderSpecLister) List(selector labels.Selector) (ret []*v1alpha1.BaremetalMachineProviderSpec, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BaremetalMachineProviderSpec))
	})
	return ret, err
}

// BaremetalMachineProviderSpecs returns an object that can list and get BaremetalMachineProviderSpecs.
func (s *baremetalMachineProviderSpecLister) BaremetalMachineProviderSpecs(namespace string) BaremetalMachineProviderSpecNamespaceLister {
	return baremetalMachineProviderSpecNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BaremetalMachineProviderSpecNamespaceLister helps list and get BaremetalMachineProviderSpecs.
type BaremetalMachineProviderSpecNamespaceLister interface {
	// List lists all BaremetalMachineProviderSpecs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.BaremetalMachineProviderSpec, err error)
	// Get retrieves the BaremetalMachineProviderSpec from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.BaremetalMachineProviderSpec, error)
	BaremetalMachineProviderSpecNamespaceListerExpansion
}

// baremetalMachineProviderSpecNamespaceLister implements the BaremetalMachineProviderSpecNamespaceLister
// interface.
type baremetalMachineProviderSpecNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BaremetalMachineProviderSpecs in the indexer for a given namespace.
func (s baremetalMachineProviderSpecNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BaremetalMachineProviderSpec, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BaremetalMachineProviderSpec))
	})
	return ret, err
}

// Get retrieves the BaremetalMachineProviderSpec from the indexer for a given namespace and name.
func (s baremetalMachineProviderSpecNamespaceLister) Get(name string) (*v1alpha1.BaremetalMachineProviderSpec, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("baremetalmachineproviderspec"), name)
	}
	return obj.(*v1alpha1.BaremetalMachineProviderSpec), nil
}
