/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/apis/baremetalproviderconfig/v1alpha1"
	scheme "github.com/redhat-nfvpe/cluster-api-provider-baremetal/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BaremetalMachineProviderConfigsGetter has a method to return a BaremetalMachineProviderConfigInterface.
// A group's client should implement this interface.
type BaremetalMachineProviderConfigsGetter interface {
	BaremetalMachineProviderConfigs(namespace string) BaremetalMachineProviderConfigInterface
}

// BaremetalMachineProviderConfigInterface has methods to work with BaremetalMachineProviderConfig resources.
type BaremetalMachineProviderConfigInterface interface {
	Create(*v1alpha1.BaremetalMachineProviderConfig) (*v1alpha1.BaremetalMachineProviderConfig, error)
	Update(*v1alpha1.BaremetalMachineProviderConfig) (*v1alpha1.BaremetalMachineProviderConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.BaremetalMachineProviderConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.BaremetalMachineProviderConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BaremetalMachineProviderConfig, err error)
	BaremetalMachineProviderConfigExpansion
}

// baremetalMachineProviderConfigs implements BaremetalMachineProviderConfigInterface
type baremetalMachineProviderConfigs struct {
	client rest.Interface
	ns     string
}

// newBaremetalMachineProviderConfigs returns a BaremetalMachineProviderConfigs
func newBaremetalMachineProviderConfigs(c *BaremetalproviderconfigV1alpha1Client, namespace string) *baremetalMachineProviderConfigs {
	return &baremetalMachineProviderConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the baremetalMachineProviderConfig, and returns the corresponding baremetalMachineProviderConfig object, and an error if there is any.
func (c *baremetalMachineProviderConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	result = &v1alpha1.BaremetalMachineProviderConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BaremetalMachineProviderConfigs that match those selectors.
func (c *baremetalMachineProviderConfigs) List(opts v1.ListOptions) (result *v1alpha1.BaremetalMachineProviderConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BaremetalMachineProviderConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested baremetalMachineProviderConfigs.
func (c *baremetalMachineProviderConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a baremetalMachineProviderConfig and creates it.  Returns the server's representation of the baremetalMachineProviderConfig, and an error, if there is any.
func (c *baremetalMachineProviderConfigs) Create(baremetalMachineProviderConfig *v1alpha1.BaremetalMachineProviderConfig) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	result = &v1alpha1.BaremetalMachineProviderConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		Body(baremetalMachineProviderConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a baremetalMachineProviderConfig and updates it. Returns the server's representation of the baremetalMachineProviderConfig, and an error, if there is any.
func (c *baremetalMachineProviderConfigs) Update(baremetalMachineProviderConfig *v1alpha1.BaremetalMachineProviderConfig) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	result = &v1alpha1.BaremetalMachineProviderConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		Name(baremetalMachineProviderConfig.Name).
		Body(baremetalMachineProviderConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the baremetalMachineProviderConfig and deletes it. Returns an error if one occurs.
func (c *baremetalMachineProviderConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *baremetalMachineProviderConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched baremetalMachineProviderConfig.
func (c *baremetalMachineProviderConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BaremetalMachineProviderConfig, err error) {
	result = &v1alpha1.BaremetalMachineProviderConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("baremetalmachineproviderconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
